const { EmbedBuilder } = require("discord.js");

function formatNumber(value) {
  return Number(value || 0).toLocaleString("en-US");
}

function medalForRank(index) {
  return ["🥇", "🥈", "🥉", "4️⃣", "5️⃣"][index] || `${index + 1}.`;
}

function displayName(entry) {
  return String(entry.displayName || entry.tag || entry.username || entry.userId || "Unknown")
    .replace(/\s+/g, " ")
    .trim();
}

function buildMemberRankingEmbed(rankings, options = {}) {
  const top = Array.isArray(rankings) ? rankings.slice(0, 5) : [];
  const updatedBy = options.updatedBy || null;

  const embed = new EmbedBuilder()
    .setColor(0xd4af37)
    .setTitle("🏆 Season Leaderboard — Bullet Echo")
    .setDescription(
      top.length
        ? "Keep grinding. Every contribution helps the syndicate grow."
        : "No ranking data has been saved yet.",
    )
    .setFooter({ text: "XPRO Ranking System • Private leaderboard preview" })
    .setTimestamp();

  if (!top.length) {
    embed.addFields({
      name: "No data",
      value: "Use `/ranking set` to add the first season scores.",
      inline: false,
    });
    return embed;
  }

  top.forEach((entry, index) => {
    embed.addFields({
      name: `${medalForRank(index)} Rank #${index + 1}`,
      value: `**${displayName(entry)}**\n⭐ Season Score: **${formatNumber(entry.season)}**`,
      inline: false,
    });
  });

  const totalSeason = top.reduce((sum, entry) => sum + Number(entry.season || 0), 0);

  embed.addFields({
    name: "📊 Top 5 Total",
    value: `**${formatNumber(totalSeason)}** season points`,
    inline: false,
  });

  if (updatedBy) {
    embed.addFields({
      name: "Generated by",
      value: updatedBy,
      inline: false,
    });
  }

  return embed;
}

module.exports = {
  buildMemberRankingEmbed,
  formatNumber,
};
