const { EmbedBuilder } = require("discord.js");

function formatNumber(value) {
  return Number(value || 0).toLocaleString("en-US");
}

function medalForRank(index) {
  return ["🥇", "🥈", "🥉", "4️⃣", "5️⃣"][index] || `${index + 1}.`;
}

function displayName(entry) {
  return String(entry.displayName || entry.tag || entry.username || entry.userId || "Unknown")
    .replace(/\s+/g, " ")
    .trim();
}

function truncateName(value, maxLength = 18) {
  const name = displayName({ displayName: value });
  if (name.length <= maxLength) return name;
  return `${name.slice(0, maxLength - 1)}…`;
}

function padRight(value, length) {
  const str = String(value || "");
  if (str.length >= length) return str;
  return str + " ".repeat(length - str.length);
}

function padLeft(value, length) {
  const str = String(value || "");
  if (str.length >= length) return str;
  return " ".repeat(length - str.length) + str;
}

function buildLeaderboardTable(rankings, startRank = 1, limit = 5) {
  const rows = rankings.slice(0, limit).map((entry, index) => {
    const rankNumber = startRank + index;
    const rank = rankNumber <= 5 ? `${medalForRank(rankNumber - 1)} ${rankNumber}` : `#${rankNumber}`;
    const player = truncateName(displayName(entry), 18);
    const season = formatNumber(entry.season);

    return `${padRight(rank, 5)} | ${padRight(player, 18)} | ${padLeft(season, 9)}`;
  });

  return [
    "RANK  | PLAYER             | SEASON",
    "──────┼────────────────────┼──────────",
    ...rows,
  ].join("\n");
}

function buildMemberRankingEmbed(rankings, options = {}) {
  const top = Array.isArray(rankings) ? rankings.slice(0, 5) : [];
  const updatedBy = options.updatedBy || null;

  const embed = new EmbedBuilder()
    .setColor(0xf1c40f)
    .setTitle("🏆 XPRO SEASON LEADERBOARD")
    .setDescription(
      top.length
        ? "**Top 5 Bullet Echo season contributors**\nRank → Player → Season score."
        : "No ranking data has been saved yet.",
    )
    .setFooter({ text: "XPRO Ranking System • Private leaderboard preview" })
    .setTimestamp();

  if (!top.length) {
    embed.addFields({
      name: "No data",
      value: "Use `/ranking set` or `/ranking reload` to add the first season scores.",
      inline: false,
    });
    return embed;
  }

  const champion = top[0];
  const totalSeason = top.reduce((sum, entry) => sum + Number(entry.season || 0), 0);

  embed.addFields(
    {
      name: "📋 Leaderboard Table",
      value: `\`\`\`text\n${buildLeaderboardTable(top, 1, 5)}\n\`\`\``,
      inline: false,
    },
    {
      name: "👑 Season Champion",
      value: `${medalForRank(0)} **${truncateName(displayName(champion), 32)}** — **${formatNumber(champion.season)}**`,
      inline: false,
    },
    {
      name: "📊 Top 5 Total",
      value: `**${formatNumber(totalSeason)}** season points`,
      inline: false,
    },
  );

  if (updatedBy) {
    embed.addFields({
      name: "Generated by",
      value: updatedBy,
      inline: false,
    });
  }

  return embed;
}

function buildFullRankingEmbeds(rankings, options = {}) {
  const entries = Array.isArray(rankings) ? rankings : [];
  const pageSize = options.pageSize || 10;
  const pages = [];

  if (!entries.length) {
    return [
      new EmbedBuilder()
        .setColor(0xf1c40f)
        .setTitle("📜 FULL SEASON RANKING")
        .setDescription("No ranking data has been saved yet."),
    ];
  }

  for (let start = 0; start < entries.length; start += pageSize) {
    const chunk = entries.slice(start, start + pageSize);
    const page = Math.floor(start / pageSize) + 1;
    const totalPages = Math.ceil(entries.length / pageSize);

    pages.push(
      new EmbedBuilder()
        .setColor(0xf1c40f)
        .setTitle("📜 FULL SEASON RANKING")
        .setDescription(`\`\`\`text\n${buildLeaderboardTable(chunk, start + 1, pageSize)}\n\`\`\``)
        .setFooter({ text: `Page ${page}/${totalPages} • ${entries.length} members` })
        .setTimestamp(),
    );
  }

  return pages.slice(0, 10);
}

module.exports = {
  buildFullRankingEmbeds,
  buildMemberRankingEmbed,
  formatNumber,
};
